[theme]
base = "light"
primaryColor = "#1d4ed8"
backgroundColor = "#f0f4ff"
secondaryBackgroundColor = "#e0eaff"
textColor = "#1e3a5f"
font = "sans serif"

[server]
#headless = true
# port = 8501
#enableCORS = false
